### PR TITLE
Improvements and fixes

### PR DESCRIPTION
**Pull request by SamyPesse**
This PR adds an option `default` to disable default `quote` alert. This also fixes a bug that is causing all blockquotes from being replaced.

### CODE REVIEW

**Comment by leesei** [comment]
Would you mind also updating the README?

**Comment by SamyPesse** [comment]
@leesei done!

**Comment by erixtekila** [comment]
Thanks !

**Comment by SamyPesse** [comment]
Awesome! Thanks :+1: Can you publish a new release ?

**Pull request merged**
